### ISSUE TITLE
Android: QuantcastClient.setEnableLocationGathering() doesn't resolve

### ISSUE THREAD

**Issue by dpolivy** [quantcast/phonegap-measurement#7]
Trying to build android with the latest release, I get this compile error:

````
C:\git\MobileApp\platforms\android\src\com\quantcast\phonegapplugin\QuantcastMeasurementPlugin.java:40: error: cannot find symbol
            QuantcastClient.setEnableLocationGathering(args.getBoolean(0));
                           ^
  symbol:   method setEnableLocationGathering(boolean)
  location: class QuantcastClient
````

It doesn't look like QuantcastMeasurementPlugin.java has changed recently, but the Android SDK has. It looks to have been removed [here](https://github.com/quantcast/android-measurement/commit/921ba64843ca1e81b01bbea667accb3d9b61d76a#diff-efcb319a0c26ec9f22d06bb5693314b4L253). Has this function moved somewhere else?

**Comment by SmithKevin** [comment]
Yeah, we refactored the location code to make it completely optional as some people didn't even like have GPS related code in their app.   We kept left in the old setEnableLocationGathering method for backwards compatibility, but looks like it was finally removed completely in the last version.  The new method is instead here QCLocation.setEnableLocationGathering().    

Is your app currently using GPS?   I am debating on just removing it completely from phonegap since most people don't use it and it doesn't add a whole lot to the Quantcast Profile.

**Comment by dpolivy** [comment]
Nope, we're not using GPS, so it's fine to get rid of this method from our perspective.

**Comment by SmithKevin** [comment]
I have removed the offending code.  I did leave it in the javascript just so it doesn't cause problems if anyone else if using it, but it will no longer turn on the GPS.

**Comment by dpolivy** [comment]
Thanks!
